### PR TITLE
Workaround for bug where partioned files are not created as expected.

### PR DESCRIPTION
**Pull request by jgriss**
When sorting p-values multiple "part files" are created. For some
reason, these files are not created under certain conditions. All
functions that expect these files subsequently break.

This workaround simply ignores any missing files.

### CODE REVIEW

**Comment by jgriss** [comment]
Dear Lukas,

I haven't found the reason for this behaviour. I believe that the hashBin is not calculated correctly under certain conditions.

One question: Where do you get the "scannr1.scannr" and "scannr2.scannr" in PValueTriplets from? Are these taken from the files or generated by your code based on the spectra's indices in the file (so you can be sure they are f.e. 0-based and always increment by one etc.)?

**Comment by MatthewThe** [comment]
Are the files with pvalues created (i.e. <mass_bin>.dat.pvalues.dat), and if so, how large are they?

scannr1.scannr and scannr2.scannr are taken from the input files and are assumed to fit in an unsigned int.

**Comment by jgriss** [comment]
Based on your comment I've double checked the output and found the following line quite frequently:
Warning: could not extract scannr. Returning scannr 0

The issue is cause in SpectrumHandler.cpp:27 where you expect spectrum ids in the format scan1234.
In case of MGF files (which I am using) the returned id format is "index=1234".

This then breaks your hashing function which furthermore causes the creation of the subsequent hashed files to fail (everything is written to the first file since all spectra get the hash of "0").

Does this make sense?

**Comment by jgriss** [comment]
This seems to be solving the issue for MGF files. Only the change in SpectrumHandler.cpp is relevant.

**Comment by MatthewThe** [comment]
Yes, that definitely makes sense. Thanks for the fix!

**Comment by MatthewThe** [comment]
Actually I realised that the offset for reading the scannr should be one less, as we previously expected a format of scan=1234 and not scan1234. I will fix it in the main branch.

**Comment by jgriss** [comment]
I think it actually is "scan=1234" so your code is fine on that end.

**Comment by MatthewThe** [comment]
I actually meant that the offset for the index=1234 was off by one in your pull request. The substr(7) should be substr(6), which I changed on the master branch.

**Pull request merged**
