### PR TITLE
Replacing the use of spectrum id by the spectrum index

### PR DESCRIPTION
**Pull request by jgriss**
The spectrum id format depends on the underlying filesystem. Therefore, the code will always break if some unexpected conversion is done. The spectrum index is always the 0-based index of the spectrum in the file and thus filetype independent.

Would this approach work for you?

### CODE REVIEW

**Comment by MatthewThe** [comment]
I agree that it would be more robust. However, in our pipeline the index and scannr become distinct due to filtering steps that remove spectra and the scannr is the entity reported in search engine results. I would prefer a solution where we try to find the scannr in either the scan=1234 or index=1234 (and possibly other formats we encounter in the future), and using the spectrum index if these are not present.

**Comment by jgriss** [comment]
If you remove the comments above that I added that's the behaviour you get. Then the spectrum->index is used as a fallback instead of "0".

**Comment by jgriss** [comment]
Btw. there was a bug in my original commit > substr should start at offset 6. Fixed in this pull request.

**Comment by jgriss** [comment]
One other comment about the spectrum id: this can be a hugely heterogeneous format. Especially if you look at the id formats commonly found in mzML files. I'm not convinced that you will be able to create a generic function for that.

But finding a more robust solution to this issue will greatly increase maraclusters usability.

**Comment by jgriss** [comment]
Hi,
This is the first version that worked for me. I've adapted the getScannr function to use the index as a fallback. Additionally, I had to ignore missing files in a few places. Otherwise the program would crash. This now produced clustering results for me.

**Comment by MatthewThe** [comment]
Thanks, the missing files are a little bit concerning, but ignoring them instead of crashing the program is definitely a better alternative.

**Pull request merged**
